<h1>GEOSPATIAL (Global Terrorist Analysis) </h1>
<h2>INCLUSIVE YEAR 1970 - 2017</h2>
<h3>Analyst: Meloujean Ligon</h3>

In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 
import folium
from folium.plugins import HeatMap
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('datasets\\Global_terrorist.csv', encoding='ISO-8859-1')

<h1 style="text-align: center; color: blue;">REGIONAL ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [3]:
region1 = df[df['region_txt'] == 'Southeast Asia']

In [4]:
region2 = region1[region1['iyear'] >= 2004]

In [5]:
region3 = region2[region2['attacktype1_txt'] == 'Armed Assault']

In [6]:
region4 = region3[region3['nkill'] >= 10]

<h1>DATA AGGREGATION</h1>

In [7]:
region_final = region4.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
region_final

     latitude   longitude  incident_count
0   -3.721569  138.060511               1
1    5.933025  121.100058               1
2    6.077377  121.082137               1
3    6.210408  101.820757               1
4    6.497216  122.105141               1
5    6.501935  122.123761               1
6    6.548956  101.638533               1
7    6.644421  122.273133               1
8    6.898558  124.476696               1
9    8.020031  124.056593               1
10   8.182602  124.114554               1
11   9.073155  125.890240               1
12  12.218140  123.509510               1
13  14.031391  122.113091               1
14  16.670038  121.717230               1
15  16.701617  120.974655               1
16  16.992500  120.734228               1
17  20.431944   98.165000               1
18  20.816667   92.366667               1
19  22.036199   98.133856               1
20  23.693281   98.772316               1
21  23.830851   98.538749               1

<h1>Use of FOLIUM FOR GEOSPATIAL</h1>

<h3> Converting Pandas Data Frame into Python List</h3>

In [8]:
region_final["normalize_data"] = region_final['incident_count'] - region_final['incident_count'].min() / \
                                region_final['incident_count'].max() - region_final['incident_count']

region_heatmap = region_final[['latitude', 'longitude', 'incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [9]:
region_map = folium.Map(location=[10, 105], zoom_start=4)

<h3> Add Heatmap Layer </h3>

In [10]:
HeatMap(region_heatmap).add_to(region_map)

In [11]:
region_map.save('regional_analysis.html')
print("data save to regional_analysis.html")

data save to regional_analysis.html

In [12]:
region_map

<h2>INSIGHT 1</h2>

<h3>Deadly armed assault incidents in Southeast Asia from 2004-2017 were mainly focused in three areas: southern Philippines, Myanmar-Thailand border, and parts of southern Thailand. The most intense activity occurred in Mindanao, Philippines, where militant groups like Abu Sayyaf were active during this period. Lower intensity hotspots are also visible near Manila and in Indonesia's eastern regions, suggesting that while major conflicts were concentrated in specific areas, terrorist violence affected multiple countries across the region.</h3>

<h1 style="text-align: center; color: blue;">NATIONALITY ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [13]:
national1 = df[df['natlty1_txt'] == 'Afghanistan']

In [14]:
national2 = national1[national1['weaptype1_txt'] == 'Explosives']

<h1>DATA AGGREGATION</h1>

In [15]:
national3 = national2.groupby(['latitude','longitude']).size().reset_index(name='incident_count')
national3

       latitude  longitude  incident_count
0     28.312161  65.663892               1
1     30.094363  65.285708               1
2     30.120278  65.180833               1
3     30.132474  62.260848               1
4     30.134523  62.262663               3
...         ...        ...             ...
2276  37.523997  65.742987               1
2277  37.527050  65.760803               1
2278  37.624012  70.581866               1
2279  37.627018  70.716847               1
2280  37.997490  23.762728               1

[2281 rows x 3 columns]

<h1>Use of FOLIUM FOR GEOSPATIAL</h1>

<h3> Converting Pandas Data Frame into Python List</h3>

In [16]:
national3["normalize_data"] = national3['incident_count'] - national3['incident_count'].min() / \
                                national3['incident_count'].max() - national3['incident_count']

national_heatmap = national3[['latitude', 'longitude', 'incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [17]:
national_map = folium.Map(location=[34, 67], zoom_start=6)

<h3> Add Heatmap Layer </h3>

In [18]:
HeatMap(national_heatmap).add_to(national_map)

In [19]:
national_map

<h2>INSIGHT 2</h2>
<H3> Afghanistan experienced extremely high concentrations of terrorist incidents across most of its territory between 1970-2017, with the most intense activity (deep red) covering both the eastern border regions near Pakistan and central provinces. Major hotspots appear near Kabul, Kandahar, and along the northern borders, demonstrating how terrorism permeated almost the entire country rather than being confined to specific regions. The widespread and intense nature of these explosive-related incidents reflects Afghanistan's prolonged exposure to conflict involving various terrorist groups, including Taliban and Al-Qaeda operations. </H3>

<h1 style="text-align: center; color: blue;">TARGET ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [20]:
    target1 = df[df['targsubtype1_txt'] == 'Government Personnel (excluding police, military)']
    target2 = target1[target1['country_txt'] == 'Pakistan']

<h1>DATA AGGREGATION</h1>

In [21]:
target3 = target2.groupby(['latitude','longitude']).size().reset_index(name='incident_count')
target3

      latitude  longitude  incident_count
0    24.891115  67.143311              43
1    25.044537  66.874672               2
2    25.054159  67.021955               1
3    25.145800  62.326557               1
4    25.267860  63.460991               2
..         ...        ...             ...
188  35.438093  73.935982               1
189  35.560714  71.797266               1
190  35.918091  74.289803               2
191  35.920160  74.307975               1
192  36.337837  73.837770               1

[193 rows x 3 columns]

<h1>Use of FOLIUM FOR GEOSPATIAL</h1>

<h3> Converting Pandas Data Frame into Python List</h3>

In [22]:
target3["normalize_data"] = target3['incident_count'] - target3['incident_count'].min() / \
                                target3['incident_count'].max() - target3['incident_count']

target_heatmap = target3[['latitude', 'longitude', 'incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [23]:
target_map = folium.Map(location=[30, 69], zoom_start=6)

<h3> Add Heatmap Layer </h3>

In [24]:
HeatMap(target_heatmap).add_to(target_map)

In [25]:
target_map

<h2>INSIGHT 3</h2>
<H2>The heatmap shows attacks targeting government personnel (excluding police and military) in Pakistan from 1970-2017, revealing distinct hotspot patterns. The most intense concentrations (red areas) appear along the Afghanistan-Pakistan border region and in multiple clusters throughout Pakistan's territory, particularly in what appears to be Balochistan and near major cities. These patterns indicate that terrorist groups strategically target government officials in both border regions and urban centers, likely to undermine state authority and governance structures. The distribution suggests a deliberate campaign against civil administration, with attacks concentrated in areas known for separatist movements and extremist group activities.</H2>

<h1 style="text-align: center; color: blue;">CASUALTY ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [26]:
casualty1 = df[df['nkill'] >= 10]
casualty2 = casualty1[casualty1['attacktype1_txt'] == 'Hostage Taking (Kidnapping)']
casualty3 = casualty2[casualty2['country_txt'] == 'Iraq']

<h1>DATA AGGREGATION</h1>

In [27]:
casualty4 = casualty3.groupby(['latitude','longitude']).size().reset_index(name='incident_count')
casualty4

     latitude  longitude  incident_count
0   30.510054  47.778095               1
1   32.469238  44.416637               2
2   32.867008  44.220455               1
3   32.984990  44.356760               1
4   33.036390  40.283332               1
5   33.038056  40.284444               1
6   33.303566  44.371773               4
7   33.349159  43.784199               2
8   33.397812  43.706276               2
9   33.403057  43.911865               1
10  33.416713  43.299752               2
11  33.420948  43.295662               3
12  33.453312  43.372253               1
13  33.509320  43.220707               1
14  33.530734  44.274292               1
15  33.633297  42.816623               1
16  33.633442  42.816579               1
17  33.633896  42.832081               2
18  33.669689  44.381317               1
19  33.683266  43.473259               2
20  33.691582  44.439841               1
21  33.693409  44.796085               1
22  33.743240  44.623825               2
23  33.850297  42.550000               1
24  33.864799  42.536385               2
25  33.997047  44.866611               1
26  34.057114  44.218292               1
27  34.100723  45.051960               1
28  34.208416  43.890713               1
29  34.271765  44.682169               1
30  34.363503  41.115997               3
31  34.621521  43.668377               1
32  35.227327  43.825115               1
33  35.238808  43.510903               1
34  35.271023  43.458084               1
35  35.324825  43.766922               3
36  35.325105  43.767265               1
37  35.326122  43.780811               2
38  35.466667  44.316667               1
39  35.485666  43.240378               1
40  35.542674  43.261805               1
41  35.700397  43.280434               1
42  35.798130  43.294178               3
43  35.995880  42.829136               1
44  36.045059  41.716717               2
45  36.144398  43.310085               1
46  36.148633  42.989676               1
47  36.158558  43.255100               3
48  36.177341  41.910160               1
49  36.184868  43.207314               1
50  36.319386  41.861473               2
51  36.320000  41.860000               1
52  36.322500  41.864167               1
53  36.354145  43.143570              30
54  36.376823  42.448875               2

<h1>Use of FOLIUM FOR GEOSPATIAL</h1>

<h3> Converting Pandas Data Frame into Python List</h3>

In [28]:
casualty4["normalize_data"] = casualty4['incident_count'] - casualty4['incident_count'].min() / \
                                casualty4['incident_count'].max() - casualty4['incident_count']

casualty_heatmap = casualty4[['latitude', 'longitude', 'incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [29]:
casualty_map = folium.Map(location=[33, 44], zoom_start=6)

<h3> Add Heatmap Layer </h3>

In [30]:
HeatMap(casualty_heatmap).add_to(casualty_map)

In [31]:
casualty_map

<h2>INSIGHT 4</h2>
<h3>The heatmap reveals high-casualty kidnapping incidents (10+ deaths) in Iraq concentrate in two primary regions: northern Iraq near the Kurdish territories/Mosul area and central Iraq around Baghdad. These deadly kidnapping hotspots correlate with periods of intense sectarian violence and ISIS activity, particularly from 2003-2017. The geographic pattern demonstrates how high-casualty kidnappings were tactically deployed in areas of strategic importance, targeting ethnic boundaries and political centers rather than occurring randomly throughout the country. The minimal activity in southern Iraq suggests these extreme tactics were less prevalent in predominantly Shia regions, pointing to the sectarian dimension of terrorist kidnapping operations in Iraq.</h3>

<h1 style="text-align: center; color: blue;">ATTACK TYPE ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [32]:
attack1 = df[df['attacktype1_txt'] == 'Facility/Infrastructure Attack']
attack2 = attack1[attack1['region_txt'] == 'Middle East & North Africa']

<h1>DATA AGGREGATION</h1>

In [33]:
attack3 = attack2.groupby(['latitude','longitude']).size().reset_index(name='incident_count')
attack3

      latitude  longitude  incident_count
0    12.825647  44.846416               6
1    12.834629  44.921983               1
2    12.867085  44.981911               2
3    13.129726  45.385571               2
4    13.178143  44.632399               1
..         ...        ...             ...
489  41.106178  28.689863             132
490  41.112950  42.702280               1
491  41.218847  36.620790               1
492  41.292811  36.329505               1
493  41.318199  36.315567               1

[494 rows x 3 columns]

<h1>Use of FOLIUM FOR GEOSPATIAL</h1>

<h3> Converting Pandas Data Frame into Python List</h3>

In [34]:
attack3["normalize_data"] = attack3['incident_count'] - attack3['incident_count'].min() / \
                                attack3['incident_count'].max() - attack3['incident_count']

attack_heatmap = attack3[['latitude', 'longitude', 'incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [35]:
attack_map = folium.Map(location=[26, 30], zoom_start=4)

<h3> Add Heatmap Layer </h3>

In [36]:
HeatMap(attack_heatmap).add_to(attack_map)

In [37]:
attack_map

<h2>INSIGHT 5</h2>
<H3>The heatmap reveals facility/infrastructure attacks in the Middle East & North Africa (1970-2017) concentrate in several distinct zones, with the most intense activity (deep red) occurring in Iraq, Syria, and Yemen. Secondary hotspots (yellow/orange) appear in Algeria, Libya, and parts of Turkey and Iran, while a significant concentration also appears in Istanbul/Western Turkey. The pattern demonstrates how infrastructure targeting follows geopolitical instability, with the highest concentrations in war-torn countries where degrading critical infrastructure delivers strategic advantages to terrorist groups. The visualization shows that facility attacks are not randomly distributed but follow clear regional patterns, targeting areas with critical economic assets and fragile governance structures.</H3>