<h1>CHICAGO CRIMES ANALYSIS</h1>
<H2>Analyst: Meloujean Ligon</H2>

In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 
import folium
from folium.plugins import HeatMap
warnings.filterwarnings('ignore')

In [2]:
chicago = pd.read_csv('datasets//Chicago_Crimes.csv', encoding='ISO-8859-1')

In [3]:
chicago

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13439321,JH237424,04/14/2024 12:00:00 AM,040XX S PRAIRIE AVE,0890,THEFT,FROM BUILDING,APARTMENT,False,False,...,3,38.0,06,1178707.0,1878256.0,2024,12/21/2024 03:40:46 PM,41.821236,-87.619921,"(41.821236024, -87.619920712)"
1,13437420,JH234779,04/14/2024 12:00:00 AM,023XX W CERMAK RD,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,COMMERCIAL / BUSINESS OFFICE,False,False,...,25,31.0,26,1161210.0,1889347.0,2024,12/21/2024 03:40:46 PM,41.852052,-87.683801,"(41.852051675, -87.683800849)"
2,13428676,JH224478,04/14/2024 12:00:00 AM,043XX W LE MOYNE ST,0917,MOTOR VEHICLE THEFT,"CYCLE, SCOOTER, BIKE WITH VIN",STREET,False,False,...,36,23.0,07,1146960.0,1909501.0,2024,12/21/2024 03:40:46 PM,41.907640,-87.735587,"(41.907640473, -87.735587478)"
3,13429357,JH225293,04/14/2024 12:00:00 AM,039XX W ADAMS ST,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,STREET,True,False,...,28,26.0,15,1150158.0,1898721.0,2024,12/21/2024 03:40:46 PM,41.877997,-87.724121,"(41.877997275, -87.724120826)"
4,13430098,JH226395,04/14/2024 12:00:00 AM,011XX W 112TH PL,0890,THEFT,FROM BUILDING,RESIDENCE,False,False,...,21,75.0,06,1170856.0,1830157.0,2024,12/21/2024 03:40:46 PM,41.689421,-87.650123,"(41.6894214, -87.650123247)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249118,13805239,JJ217509,04/12/2025 12:00:00 AM,029XX W LOGAN BLVD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,False,...,1,22.0,26,1156478.0,1917149.0,2025,04/19/2025 03:41:24 PM,41.928440,-87.700416,"(41.928439867, -87.700415972)"
249119,13804023,JJ215813,04/12/2025 12:00:00 AM,094XX S HARVARD AVE,0430,BATTERY,AGGRAVATED - OTHER DANGEROUS WEAPON,STREET,False,False,...,9,49.0,04B,1175694.0,1842631.0,2025,04/19/2025 03:41:24 PM,41.723545,-87.632040,"(41.723545182, -87.632039508)"
249120,13803926,JJ215943,04/12/2025 12:00:00 AM,084XX S VINCENNES AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,21,71.0,08B,1173850.0,1848976.0,2025,04/19/2025 03:41:24 PM,41.740998,-87.638606,"(41.74099774, -87.638606337)"
249121,13803475,JJ215338,04/12/2025 12:00:00 AM,050XX S ABERDEEN ST,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,STREET,True,False,...,20,61.0,04A,1169838.0,1871348.0,2025,04/19/2025 03:41:24 PM,41.802477,-87.652657,"(41.802477219, -87.652657244)"
249122,13804512,JJ216668,04/12/2025 12:00:00 AM,012XX W CARROLL AVE,0710,THEFT,THEFT FROM MOTOR VEHICLE,STREET,False,False,...,27,28.0,06,1168216.0,1902390.0,2025,04/19/2025 03:41:24 PM,41.887694,-87.657710,"(41.887694407, -87.657710204)"

In [4]:
chicago['Primary Type'].value_counts()

Primary Type
THEFT                                59201
BATTERY                              44579
CRIMINAL DAMAGE                      27094
ASSAULT                              22615
MOTOR VEHICLE THEFT                  19604
OTHER OFFENSE                        16781
DECEPTIVE PRACTICE                   14991
BURGLARY                              8443
ROBBERY                               8200
WEAPONS VIOLATION                     7164
NARCOTICS                             6627
CRIMINAL TRESPASS                     5045
OFFENSE INVOLVING CHILDREN            1597
CRIMINAL SEXUAL ASSAULT               1573
SEX OFFENSE                           1210
PUBLIC PEACE VIOLATION                1006
INTERFERENCE WITH PUBLIC OFFICER       771
HOMICIDE                               553
STALKING                               520
ARSON                                  452
PROSTITUTION                           287
CONCEALED CARRY LICENSE VIOLATION      249
LIQUOR LAW VIOLATION                   192
INTIMIDATION                           145
KIDNAPPING                             105
OBSCENITY                               53
HUMAN TRAFFICKING                       24
GAMBLING                                18
PUBLIC INDECENCY                        13
OTHER NARCOTIC VIOLATION                 7
NON-CRIMINAL                             4
Name: count, dtype: int64

In [5]:
chicago['Primary Type'].unique()

array(['THEFT', 'OTHER OFFENSE', 'MOTOR VEHICLE THEFT',
       'WEAPONS VIOLATION', 'BATTERY', 'ASSAULT',
       'CRIMINAL SEXUAL ASSAULT', 'CRIMINAL TRESPASS', 'CRIMINAL DAMAGE',
       'DECEPTIVE PRACTICE', 'SEX OFFENSE', 'ROBBERY', 'NARCOTICS',
       'HOMICIDE', 'INTERFERENCE WITH PUBLIC OFFICER', 'BURGLARY',
       'ARSON', 'OFFENSE INVOLVING CHILDREN', 'INTIMIDATION',
       'PUBLIC PEACE VIOLATION', 'CONCEALED CARRY LICENSE VIOLATION',
       'KIDNAPPING', 'STALKING', 'LIQUOR LAW VIOLATION', 'PROSTITUTION',
       'GAMBLING', 'OBSCENITY', 'PUBLIC INDECENCY', 'HUMAN TRAFFICKING',
       'OTHER NARCOTIC VIOLATION', 'NON-CRIMINAL'], dtype=object)

In [6]:
chicago.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [7]:
chicago['Date'] = pd.to_datetime(chicago['Date'], errors='coerce')

<h1 style="text-align: center; color: blue;">THEFT ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [8]:
theft1 = chicago[chicago['Primary Type'] == 'THEFT']
theft2 = theft1[theft1['Location Description'] == 'STREET']

<h1>DATA AGGREGATION</h1>

In [9]:
theft3 = theft2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
theft3

        Latitude  Longitude  incident_count
0      41.644608 -87.598848               1
1      41.645732 -87.542389               1
2      41.646066 -87.616354               1
3      41.647225 -87.542802               1
4      41.647922 -87.613329               1
...          ...        ...             ...
12093  42.021723 -87.673071               1
12094  42.021993 -87.674246               1
12095  42.022236 -87.667332               1
12096  42.022256 -87.669341               1
12097  42.022548 -87.676139               1

[12098 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [10]:
theft3["normalize_data"] = theft3['incident_count'] - theft3['incident_count'].min() / \
                                theft3['incident_count'].max() - theft3['incident_count']

theft_heatmap = theft3[['Latitude', 'Longitude', 'incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [11]:
theft_map =  folium.Map(location = [42, -87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [12]:
HeatMap(theft_heatmap).add_to(theft_map)

In [13]:
theft_map.save('theft.html')
print('data save to theft.html')

data save to theft.html

In [14]:
theft_map

<h1 style="text-align: center; color: blue;">OTHER OFFENSE ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [15]:
otheroffense1 = chicago[chicago['Primary Type'] == 'OTHER OFFENSE']
otheroffense2 = otheroffense1[otheroffense1['Year'] >= 2024]
otheroffense3 = otheroffense2[otheroffense2['Beat'] >= 2000]

<h1>DATA AGGREGATION</h1>

In [16]:
otheroffense_final = otheroffense3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
otheroffense_final

       Latitude  Longitude  incident_count
0     41.678238 -87.680734               3
1     41.678313 -87.681960               1
2     41.678507 -87.673088               1
3     41.678543 -87.671228               1
4     41.678613 -87.662497               1
...         ...        ...             ...
2197  42.022258 -87.669614               1
2198  42.022520 -87.671344               1
2199  42.022521 -87.671024               1
2200  42.022525 -87.672253               1
2201  42.022535 -87.673435               1

[2202 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [17]:
otheroffense_final["normalize_data"] = otheroffense_final['incident_count'] - otheroffense_final['incident_count'].min() / \
                                otheroffense_final['incident_count'].max() - otheroffense_final['incident_count']

otheroffense_heatmap = otheroffense_final[['Latitude', 'Longitude', 'incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [18]:
otheroffense_map =  folium.Map(location = [42,-87], zoom_start = 7)
HeatMap(otheroffense_heatmap).add_to(otheroffense_map)

In [19]:
otheroffense_map.save('other_offense.html')
print('data save to other_offense.html')

data save to other_offense.html

In [20]:
otheroffense_map

<h1 style="text-align: center; color: blue;">MOTOR VEHICLE THEFT ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [21]:
motor1 = chicago[chicago['Primary Type'] == 'MOTOR VEHICLE THEFT' ]
motor2 = motor1[motor1['Year'] >= 2024]
motor3 = motor2[motor2['Location Description'] == 'SIDEWALK']

<h1>DATA AGGREGATION</h1>

In [22]:
motor_final = motor3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
motor_final

     Latitude  Longitude  incident_count
0   41.680887 -87.634765               1
1   41.684400 -87.659160               1
2   41.721320 -87.654518               1
3   41.741165 -87.621115               1
4   41.749318 -87.668266               1
5   41.752735 -87.584435               1
6   41.753467 -87.633521               1
7   41.759016 -87.635725               1
8   41.771951 -87.685181               1
9   41.779739 -87.645517               1
10  41.793882 -87.624067               1
11  41.794038 -87.663799               1
12  41.809582 -87.666205               1
13  41.811394 -87.603116               1
14  41.845691 -87.620078               1
15  41.852907 -87.627791               1
16  41.853849 -87.627105               1
17  41.867124 -87.721441               1
18  41.872872 -87.696911               1
19  41.875759 -87.705966               1
20  41.876506 -87.749273               1
21  41.878981 -87.761779               1
22  41.879290 -87.741554               1
23  41.881884 -87.640060               1
24  41.894709 -87.640759               1
25  41.895666 -87.694543               1
26  41.901628 -87.734497               1
27  41.902451 -87.666316               1
28  41.904910 -87.683063               1
29  41.907371 -87.707692               1
30  41.911684 -87.745918               1
31  41.916752 -87.670300               1
32  41.937228 -87.644305               1
33  41.948534 -87.647988               1
34  41.961947 -87.715612               1
35  41.974323 -87.653346               1
36  41.978318 -87.668338               1
37  41.991487 -87.656856               1
38  41.998162 -87.691117               1
39  41.999441 -87.696501               1
40  42.003118 -87.694062               1
41  42.004639 -87.672865               1
42  42.020771 -87.670722               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [23]:
motor_final["normalize_data"] = motor_final['incident_count'] - motor_final['incident_count'].min() / \
                                motor_final['incident_count'].max() - motor_final['incident_count']
motor_heatmap = motor_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [24]:
motor_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [25]:
HeatMap(motor_heatmap).add_to(motor_map)

In [26]:
motor_map.save('motor.html')
print('data save to motor.html')

data save to motor.html

In [27]:
motor_map


<h1 style="text-align: center; color: blue;">WEAPONS VIOLATION ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [28]:
weapons1 = chicago[chicago['Primary Type'] == 'WEAPONS VIOLATION']
weapons2 = weapons1[weapons1['District'] >= 10]
weapons3 = weapons2[weapons2['Arrest'] == False]

<h1>DATA AGGREGATION</h1>

In [29]:
weapons_final = weapons3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
weapons_final

      Latitude  Longitude  incident_count
0    41.684016 -87.669433               1
1    41.685010 -87.647648               1
2    41.685862 -87.651014               1
3    41.686117 -87.637341               1
4    41.686484 -87.634939               1
..         ...        ...             ...
912  42.019453 -87.681106               1
913  42.021179 -87.672429               1
914  42.021179 -87.672444               1
915  42.021432 -87.670715               1
916  42.021726 -87.670716               1

[917 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [30]:
weapons_final["normalize_data"] = weapons_final['incident_count'] - weapons_final['incident_count'].min() / \
                                weapons_final['incident_count'].max() - weapons_final['incident_count']
weapons_heatmap = weapons_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [31]:
weapons_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [32]:
HeatMap(weapons_heatmap).add_to(weapons_map)

In [33]:
weapons_map.save('weapons.html')
print('data save to weapons.html')

data save to weapons.html

In [34]:
weapons_map


<h1 style="text-align: center; color: blue;">BATTERY ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [35]:
battery1 = chicago[chicago['Primary Type'] == 'BATTERY']
battery2 = battery1[battery1['Year'] >= 2024]
battery3 = battery2[battery2['Location Description'] == 'SMALL RETAIL STORE']

<h1>DATA AGGREGATION</h1>

In [36]:
battery_final = battery3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
battery_final

      Latitude  Longitude  incident_count
0    41.677800 -87.642881               1
1    41.677875 -87.636277               1
2    41.680693 -87.662446               1
3    41.681989 -87.662568               1
4    41.688008 -87.642245               1
..         ...        ...             ...
373  42.018755 -87.690181               1
374  42.019383 -87.672661               1
375  42.019398 -87.674880               1
376  42.019399 -87.675049               1
377  42.019530 -87.689364               1

[378 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [37]:
battery_final["normalize_data"] = battery_final['incident_count'] - battery_final['incident_count'].min() / \
                                battery_final['incident_count'].max() - battery_final['incident_count']
battery_heatmap = battery_final[['Latitude','Longitude','incident_count']].values.tolist()

In [38]:
battery_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [39]:
HeatMap(battery_heatmap).add_to(battery_map)

In [40]:
battery_map.save('battery.html')
print('data save to battery.html')

data save to battery.html

In [41]:
battery_map


<h1 style="text-align: center; color: blue;">ASSAULT ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [42]:
assault1 = chicago[chicago['Primary Type'] == 'ASSAULT'] 
assault2 = assault1[assault1['Year'] == 2025]
assault3 = assault2[assault2['Arrest'] == True]

<h1>DATA AGGREGATION</h1>

In [43]:
assault_final = assault3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
assault_final

      Latitude  Longitude  incident_count
0    41.645378 -87.540022               1
1    41.652218 -87.618872               1
2    41.654975 -87.547146               1
3    41.656698 -87.611592               1
4    41.657209 -87.602870               1
..         ...        ...             ...
631  42.018498 -87.672983               1
632  42.019383 -87.672753               1
633  42.019399 -87.675049               1
634  42.019845 -87.666216               1
635  42.021808 -87.666774               1

[636 rows x 3 columns]

In [44]:
assault_heatmap = assault_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Converting Pandas Data Frame into Python List</h3>

In [45]:
assault_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Creating a base map </h3>

In [46]:
HeatMap(assault_heatmap).add_to(assault_map)

In [47]:
assault_map.save('assault.html')
print('data save to assault.html')

data save to assault.html

In [48]:
assault_map


<h1 style="text-align: center; color: blue;">CRIMINAL SEXUAL ASSAULT ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [49]:
criminal1= chicago[chicago['Primary Type'] == 'CRIMINAL SEXUAL ASSAULT']
criminal2 = criminal1[criminal1['Year'] >=  2024] 
criminal3 = criminal2[criminal2['Location Description'] == 'RESIDENCE']

<h1>DATA AGGREGATION</h1>

In [50]:
criminalassault_final = criminal3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count') 
criminalassault_final

      Latitude  Longitude  incident_count
0    41.652812 -87.547154               1
1    41.654741 -87.607556               1
2    41.663067 -87.638995               1
3    41.664168 -87.549548               1
4    41.668287 -87.633170               1
..         ...        ...             ...
261  42.010379 -87.663659               1
262  42.011139 -87.700929               1
263  42.015464 -87.676452               1
264  42.018498 -87.672983               1
265  42.019387 -87.696751               1

[266 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [51]:
criminalassault_heatmap = criminalassault_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [52]:
criminalassault_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [53]:
HeatMap(criminalassault_heatmap).add_to(criminalassault_map)

In [54]:
criminalassault_map.save('criminal_assault.html')
print('data save to criminal_assault.html')

data save to criminal_assault.html

In [55]:
criminalassault_map


<h1 style="text-align: center; color: blue;">CRIMINAL TRESPASS ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [56]:
criminal_trespass1 = chicago[chicago['Primary Type'] == 'CRIMINAL TRESPASS'] 
criminal_trespass2 = criminal_trespass1[criminal_trespass1['Location Description'] == 'RESIDENCE']
criminal_trespass3 = criminal_trespass2[criminal_trespass2['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [57]:
trespass_final = criminal_trespass3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
trespass_final

      Latitude  Longitude  incident_count
0    41.651431 -87.527258               1
1    41.652353 -87.610064               1
2    41.654061 -87.616338               1
3    41.658115 -87.613852               1
4    41.658424 -87.551978               1
..         ...        ...             ...
728  42.013960 -87.663128               1
729  42.014105 -87.812706               1
730  42.018193 -87.666653               1
731  42.019259 -87.702872               1
732  42.021157 -87.671013               1

[733 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [58]:
trespass_heatmap = trespass_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [59]:
trespass_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [60]:
HeatMap(trespass_heatmap).add_to(trespass_map)

In [61]:
trespass_map.save('trespass.html')
print('data save to trespass.html')

data save to trespass.html

In [62]:
trespass_map


<h1 style="text-align: center; color: blue;">CRIMINAL DAMAGE ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [63]:
criminal_damage1 = chicago[chicago['Primary Type'] == 'CRIMINAL DAMAGE']
criminal_damage2 = criminal_damage1[criminal_damage1['Description'] == 'TO VEHICLE' ]
criminal_damage3 = criminal_damage2[criminal_damage2['Year'] >= 2025]
criminal_damage4 = criminal_damage3[criminal_damage3['Arrest'] == False]

<h1>DATA AGGREGATION</h1>

In [64]:
damage_final = criminal_damage4.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
damage_final

       Latitude  Longitude  incident_count
0     41.648589 -87.539964               1
1     41.649488 -87.535028               1
2     41.650853 -87.544734               1
3     41.651127 -87.538667               1
4     41.651152 -87.544734               1
...         ...        ...             ...
2858  42.018428 -87.680454               1
2859  42.018488 -87.688962               1
2860  42.018622 -87.684541               1
2861  42.019381 -87.672393               1
2862  42.019512 -87.687171               1

[2863 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [65]:
damage_heatmap = damage_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [66]:
damage_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [67]:
HeatMap(damage_heatmap).add_to(damage_map)

In [68]:
damage_map.save('damage.html')
print('data save to damage.html')

data save to damage.html

In [69]:
damage_map


<h1 style="text-align: center; color: blue;">DECEPTIVE PRACTICE ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [70]:
deceptive1 = chicago[chicago['Primary Type'] == 'DECEPTIVE PRACTICE']
deceptive2 = deceptive1[deceptive1['Description'] == 'COUNTERFEITING DOCUMENT']
deceptive3 = deceptive2[deceptive2['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [71]:
deceptive_final = deceptive3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
deceptive_final

      Latitude  Longitude  incident_count
0    41.659882 -87.578687               1
1    41.663253 -87.640778               1
2    41.678959 -87.626319               1
3    41.691525 -87.703619               1
4    41.691843 -87.618255               1
..         ...        ...             ...
179  42.005951 -87.661023               1
180  42.009770 -87.674141               1
181  42.011991 -87.703176               1
182  42.012254 -87.691560               1
183  42.017949 -87.683462               1

[184 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [72]:
deceptive_heatmap = deceptive_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [73]:
deceptive_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [74]:
HeatMap(deceptive_heatmap).add_to(deceptive_map)

In [75]:
deceptive_map.save('deceptive.html')
print('data save to deceptive.html')

data save to deceptive.html

In [76]:
deceptive_map


<h1 style="text-align: center; color: blue;">SEX OFFENSE ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [77]:
sex1 = chicago[chicago['Primary Type'] == 'SEX OFFENSE']
sex2 = sex1[sex1['Location Description'] == 'RESIDENCE']
sex3 = sex2[sex2['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [78]:
sex_final = sex3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
sex_final

      Latitude  Longitude  incident_count
0    41.652119 -87.618720               1
1    41.653004 -87.539881               1
2    41.654185 -87.606801               1
3    41.655802 -87.604371               1
4    41.656442 -87.602333               1
..         ...        ...             ...
282  41.994634 -87.694666               1
283  41.994685 -87.693447               1
284  41.996401 -87.657643               1
285  41.999756 -87.793950               1
286  42.017040 -87.680469               1

[287 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [79]:
sex_heatmap = sex_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [80]:
sex_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [81]:
HeatMap(sex_heatmap).add_to(sex_map)

In [82]:
sex_map.save('sex.html')
print('data save to sex.html')

data save to sex.html

In [83]:
sex_map


<h1 style="text-align: center; color: blue;">ROBBERY ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [84]:
robbery1 = chicago[chicago['Primary Type'] == 'ROBBERY']
robbery2 = robbery1[robbery1['Location Description'] == 'DEPARTMENT STORE']
robbery3 = robbery2[robbery2['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [85]:
robbery_final = robbery3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
robbery_final

     Latitude  Longitude  incident_count
0   41.677810 -87.642303               1
1   41.697623 -87.595770               1
2   41.707192 -87.621743               1
3   41.736148 -87.629070               1
4   41.736346 -87.585636               1
..        ...        ...             ...
68  41.958430 -87.708156               1
69  41.961067 -87.718345               1
70  41.961379 -87.654741               1
71  41.993044 -87.660360               1
72  41.998734 -87.660613               1

[73 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [86]:
robbery_heatmap = robbery_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [87]:
robbery_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [88]:
HeatMap(robbery_heatmap).add_to(robbery_map)

In [89]:
robbery_map.save('robbery.html')
print('data save to robbery.html')

data save to robbery.html

In [90]:
robbery_map


<h1 style="text-align: center; color: blue;">NARCOTICS ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [91]:
narcotics1= chicago[chicago['Primary Type'] == 'NARCOTICS']
narcotics2 = narcotics1[narcotics1['Description'] == 'FOUND SUSPECT NARCOTICS']
narcotics3 = narcotics2[narcotics2['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [92]:
narcotics_final = narcotics3 = narcotics2[narcotics2['Year'] >= 2024].groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
narcotics_final

      Latitude  Longitude  incident_count
0    41.681894 -87.672680               1
1    41.686500 -87.628927               1
2    41.686845 -87.619456               1
3    41.692364 -87.605987               1
4    41.692570 -87.624398               2
..         ...        ...             ...
508  42.004205 -87.660839               1
509  42.012254 -87.691560               1
510  42.014216 -87.664229               1
511  42.014828 -87.698114               1
512  42.019926 -87.673090               1

[513 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [93]:
narcotics_heatmap = narcotics_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [94]:
narcotics_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [95]:
HeatMap(narcotics_heatmap).add_to(narcotics_map)

In [96]:
narcotics_map.save('narcotics.html')
print('data save to narcotics.html')

data save to narcotics.html

In [97]:
narcotics_map

<h1 style="text-align: center; color: blue;">HOMICIDE ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [98]:
homicide1 = chicago[chicago['Primary Type'] == 'HOMICIDE'] 
homicide2 = homicide1[homicide1['Location Description'] == 'APARTMENT']
homicide3 = homicide2[homicide2['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [99]:
homicide_final = homicide3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
homicide_final

     Latitude  Longitude  incident_count
0   41.652669 -87.537455               1
1   41.656398 -87.602334               1
2   41.673548 -87.616796               2
3   41.700366 -87.669866               1
4   41.739005 -87.637639               1
..        ...        ...             ...
62  41.898092 -87.750777               1
63  41.919542 -87.788530               1
64  41.943073 -87.772311               2
65  41.991349 -87.656851               1
66  41.998175 -87.703331               1

[67 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [100]:
homicide_heatmap = homicide_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [101]:
homicide_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [102]:
HeatMap(homicide_heatmap).add_to(homicide_map)

In [103]:
homicide_map.save('homicide.html')
print('data save to homicide.html')

data save to homicide.html

In [104]:
homicide_map

<h1 style="text-align: center; color: blue;">INTERFERENCE WITH PUBLIC OFFICER ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [105]:
interference_filter = chicago[chicago['Primary Type'] == 'INTERFERENCE WITH PUBLIC OFFICER']
interference_filter2 = interference_filter[interference_filter['Description'] == 'ESCAPE']
interference_filter3 = interference_filter2[interference_filter2['Arrest'] == True]

<h1>DATA AGGREGATION</h1>

In [106]:
interference_final = interference_filter3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count') 
interference_final

    Latitude  Longitude  incident_count
0  41.692570 -87.624398               1
1  41.692834 -87.604319               1
2  41.770021 -87.691334               1
3  41.801392 -87.627968               1
4  41.855357 -87.710229               1
5  41.869202 -87.670590               1
6  41.895003 -87.621528               1
7  41.903077 -87.683673               1
8  41.945864 -87.767913               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [107]:
interference_heatmap = interference_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [108]:
interference_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [109]:
HeatMap(interference_heatmap).add_to(interference_map)

In [110]:
interference_map.save('interference.html')
print('data save to interference.html')

data save to interference.html

In [111]:
interference_map

<h1 style="text-align: center; color: blue;">BURGLARY ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [112]:
burglary1 = chicago[chicago['Primary Type'] == 'BURGLARY'] 
burglary2 = burglary1[burglary1['Location Description'] == 'RESIDENCE'] 
burglary3 = burglary2[burglary2['Year'] >= 2025]

<h1>DATA AGGREGATION</h1>

In [113]:
burglary_final = burglary3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
burglary_final

      Latitude  Longitude  incident_count
0    41.651020 -87.544735               1
1    41.669623 -87.634422               1
2    41.673132 -87.653934               1
3    41.673622 -87.634551               1
4    41.677578 -87.617805               1
..         ...        ...             ...
282  42.002689 -87.772068               1
283  42.005270 -87.809967               1
284  42.011517 -87.668618               1
285  42.014624 -87.707286               1
286  42.018148 -87.669436               1

[287 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [114]:
burglary_heatmap = burglary_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [115]:
burglary_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [116]:
HeatMap(burglary_heatmap).add_to(burglary_map)

In [117]:
burglary_map.save('burglary.html')
print('data save to burglary.html')

data save to burglary.html

In [118]:
burglary_map

<h1 style="text-align: center; color: blue;">ARSON ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [119]:
arson1 = chicago[chicago['Primary Type'] == 'ARSON'] 
arson2 = arson1[arson1['Location Description'] == 'COMMERCIAL / BUSINESS OFFICE']

<h1>DATA AGGREGATION</h1>

In [120]:
arson_final = arson2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
arson_final

    Latitude  Longitude  incident_count
0  41.757524 -87.586109               1
1  41.764631 -87.687429               1
2  41.787324 -87.664412               1
3  41.819539 -87.695359               1
4  41.879667 -87.636963               1
5  41.880653 -87.634397               1
6  41.880731 -87.628741               1
7  41.909712 -87.739179               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [121]:
arson_heatmap = arson_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [122]:
arson_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [123]:
HeatMap(arson_heatmap).add_to(arson_map)

In [124]:
arson_map.save('arson.html')
print('data save to arson.html')

data save to arson.html

In [125]:
arson_map

<h1 style="text-align: center; color: blue;">OFFENSE INVOLVING CHILDREN ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [126]:
children1 = chicago[chicago['Primary Type'] == 'OFFENSE INVOLVING CHILDREN']
children2 = children1[children1['Location Description'] == 'SCHOOL - PUBLIC GROUNDS']

<h1>DATA AGGREGATION</h1>

In [127]:
children_final = children2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count') 
children_final

     Latitude  Longitude  incident_count
0   41.714598 -87.567022               3
1   41.724927 -87.623815               1
2   41.739285 -87.625537               1
3   41.740247 -87.608602               1
4   41.742271 -87.560010               1
5   41.742539 -87.653525               1
6   41.743037 -87.665986               1
7   41.747162 -87.731556               1
8   41.755202 -87.645373               1
9   41.760067 -87.556666               1
10  41.774280 -87.594515               1
11  41.778755 -87.617297               1
12  41.797182 -87.668314               1
13  41.802110 -87.685508               1
14  41.809221 -87.626902               1
15  41.827436 -87.620006               1
16  41.839398 -87.640226               1
17  41.845586 -87.731082               1
18  41.848096 -87.680633               1
19  41.862365 -87.718304               1
20  41.865501 -87.653803               1
21  41.871191 -87.624153               1
22  41.873732 -87.702226               1
23  41.894273 -87.726052               1
24  41.900099 -87.662516               1
25  41.935702 -87.749218               1
26  41.949325 -87.685902               1
27  41.954882 -87.669067               1
28  41.984032 -87.700399               1
29  42.017040 -87.677653               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [128]:
children_heatmap = children_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [129]:
children_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [130]:
HeatMap(children_heatmap).add_to(children_map)

In [131]:
children_map.save('children.html')
print('data save to children.html')

data save to children.html

In [132]:
children_map

<h1 style="text-align: center; color: blue;">INTIMIDATION ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [133]:
intimidation1 = chicago[chicago['Primary Type'] == 'INTIMIDATION'] 
intimidation2 = intimidation1[intimidation1['Location Description'] == 'STREET']

<h1>DATA AGGREGATION</h1>

In [134]:
intimidation_final = intimidation2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
intimidation_final

     Latitude  Longitude  incident_count
0   41.702733 -87.564856               1
1   41.707913 -87.646507               1
2   41.728995 -87.627046               1
3   41.747976 -87.647605               1
4   41.776323 -87.605838               1
5   41.813115 -87.622432               1
6   41.816439 -87.598547               1
7   41.837489 -87.646264               1
8   41.850494 -87.733385               1
9   41.881149 -87.624341               1
10  41.883211 -87.629907               1
11  41.894228 -87.619116               1
12  41.908431 -87.638510               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [135]:
intimidation_heatmap = intimidation_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [136]:
intimidation_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [137]:
HeatMap(intimidation_heatmap).add_to(intimidation_map)

In [138]:
intimidation_map.save('intimidation.html')
print('data save to intimidation.html')

data save to intimidation.html

In [139]:
intimidation_map

<h1 style="text-align: center; color: blue;">PUBLIC PEACE VIOLATION ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [140]:
publicpeace1 = chicago[chicago['Primary Type'] == 'PUBLIC PEACE VIOLATION']
publicpeace2 = publicpeace1[publicpeace1['Description'] == 'BOMB THREAT']

<h1>DATA AGGREGATION</h1>

In [141]:
publicpeace_final = publicpeace2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
publicpeace_final

      Latitude  Longitude  incident_count
0    41.680418 -87.662438               1
1    41.709804 -87.642909               3
2    41.721439 -87.614132               1
3    41.749547 -87.723354               1
4    41.752298 -87.605230               1
..         ...        ...             ...
113  41.990515 -87.655399               1
114  41.993293 -87.656911               1
115  41.994819 -87.786362               1
116  42.012161 -87.695649               1
117  42.013109 -87.663604               1

[118 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [142]:
publicpeace_heatmap = publicpeace_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [143]:
publicpeace_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [144]:
HeatMap(publicpeace_heatmap).add_to(publicpeace_map)

In [145]:
publicpeace_map.save('publicpeace.html')
print('data save to publicpeace.html')

data save to publicpeace.html

In [146]:
publicpeace_map

<h1 style="text-align: center; color: blue;">CONCEALED CARRY LICENSE VIOLATION ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [147]:
concealed1 = chicago[chicago['Primary Type'] == 'CONCEALED CARRY LICENSE VIOLATION']
concealed2 = concealed1[concealed1['Location Description'] == 'AIRPORT TERMINAL UPPER LEVEL - SECURE AREA']
concealed3 = concealed2[concealed2['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [148]:
concealed_final = concealed3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
concealed_final

    Latitude  Longitude  incident_count
0  41.788987 -87.741480              15
1  41.974862 -87.890372               3
2  41.976421 -87.904976               1
3  41.976454 -87.901365               1
4  41.976763 -87.900984              21
5  41.979006 -87.906463              20

<h3> Converting Pandas Data Frame into Python List</h3>

In [149]:
concealed_heatmap = concealed_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [150]:
concealed_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [151]:
HeatMap(concealed_heatmap).add_to(concealed_map)

In [152]:
concealed_map.save('concealed_license.html')
print('data save to concealed_license.html')

data save to concealed_license.html

In [153]:
concealed_map

<h1 style="text-align: center; color: blue;">KIDNAPPING ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [154]:
kidnapping1 = chicago[chicago['Primary Type'] == 'KIDNAPPING']
kidnapping2 = kidnapping1[kidnapping1['Description'] == 'CHILD ABDUCTION / STRANGER']

<h1>DATA AGGREGATION</h1>

In [155]:
kidnapping_final = kidnapping2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
kidnapping_final

     Latitude  Longitude  incident_count
0   41.651431 -87.527258               1
1   41.677911 -87.633128               1
2   41.689045 -87.655663               1
3   41.689402 -87.668825               1
4   41.691518 -87.703937               1
5   41.706272 -87.622607               1
6   41.746966 -87.601424               1
7   41.767410 -87.690652               1
8   41.767761 -87.690664               1
9   41.772940 -87.680904               1
10  41.782313 -87.598903               1
11  41.789840 -87.706207               1
12  41.793235 -87.693787               1
13  41.821768 -87.700360               1
14  41.867720 -87.705711               1
15  41.884231 -87.696670               1
16  41.902717 -87.720877               1
17  41.926400 -87.665780               1
18  41.944524 -87.766708               1
19  41.953576 -87.663529               1
20  41.958439 -87.653669               1
21  41.969783 -87.767543               1
22  41.998598 -87.685035               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [156]:
kidnapping_heatmap = kidnapping_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [157]:
kidnapping_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [158]:
HeatMap(kidnapping_heatmap).add_to(kidnapping_map)

In [159]:
kidnapping_map.save('kidnapping.html')
print('data save to kidnapping.html')

data save to kidnapping.html

In [160]:
kidnapping_map

<h1 style="text-align: center; color: blue;">STALKING ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [161]:
stalking_filter = chicago[chicago['Primary Type'] == 'STALKING'] 
stalking_filter2 = stalking_filter[stalking_filter['Location Description'] == 'RESIDENCE']
stalking_filter3 = stalking_filter2[stalking_filter2['Description'] == 'CYBERSTALKING']

<h1>DATA AGGREGATION</h1>

In [162]:
stalking_final = stalking_filter3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
stalking_filter3

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
6423,13438259,JH235843,2024-04-23 09:07:00,120XX S PERRY AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,9,53.0,08A,1177764.0,1825061.0,2024,12/21/2024 03:40:46 PM,41.675284,-87.624987,"(41.675284079, -87.624986591)"
9860,13444867,JH243101,2024-04-28 11:00:00,036XX W DOUGLAS BLVD,0583,STALKING,CYBERSTALKING,RESIDENCE,False,False,...,24,29.0,08A,1152512.0,1893219.0,2024,12/21/2024 03:40:46 PM,41.862853,-87.715623,"(41.862853002, -87.71562282)"
27580,13472591,JH278482,2024-05-22 18:04:00,001XX N LATROBE AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,False,...,37,25.0,08A,1141360.0,1900492.0,2024,12/21/2024 03:40:46 PM,41.883024,-87.756382,"(41.883023947, -87.756381654)"
39588,13510953,JH322761,2024-06-07 07:00:00,050XX W WEST END AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,False,...,28,25.0,08A,1142688.0,1900511.0,2024,12/21/2024 03:40:46 PM,41.883051,-87.751505,"(41.883051483, -87.751504636)"
43747,13493449,JH303756,2024-06-12 20:23:00,112XX S WASHTENAW AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,False,...,19,75.0,08A,1160389.0,1829963.0,2024,12/21/2024 03:40:46 PM,41.689110,-87.688448,"(41.689110447, -87.688448398)"
47871,13515520,JH329313,2024-06-18 01:00:00,099XX S PRINCETON AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,9,49.0,08A,1176045.0,1838842.0,2024,12/21/2024 03:40:46 PM,41.713140,-87.630867,"(41.713139794, -87.630867066)"
69850,13586401,JH414240,2024-07-16 15:00:00,079XX S MAPLEWOOD AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,18,70.0,08A,1160757.0,1851953.0,2024,12/21/2024 03:40:46 PM,41.749447,-87.686496,"(41.74944713, -87.686496292)"
88236,13558809,JH381997,2024-08-09 09:00:00,068XX S DAMEN AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,False,...,16,67.0,08A,1164210.0,1859136.0,2024,12/21/2024 03:40:46 PM,41.769086,-87.673641,"(41.769086368, -87.673641195)"
90991,13562836,JH386838,2024-08-13 00:00:00,035XX W LYNDALE ST,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,35,22.0,08A,1152757.0,1914736.0,2024,12/21/2024 03:40:46 PM,41.921893,-87.714153,"(41.92189295, -87.714153451)"
108581,13592897,JH422806,2024-09-05 21:00:00,074XX S MERRILL AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,7,43.0,08A,1191843.0,1855973.0,2024,12/21/2024 03:40:46 PM,41.759781,-87.572456,"(41.759780594, -87.572455541)"
145718,13651899,JH492823,2024-10-26 14:04:00,092XX S SANGAMON ST,0583,STALKING,CYBERSTALKING,RESIDENCE,False,False,...,21,73.0,08A,1171604.0,1843578.0,2024,12/21/2024 03:40:46 PM,41.726234,-87.646993,"(41.726234341, -87.64699321)"
159615,13717951,JJ112061,2024-11-15 00:01:00,062XX N CENTRAL PARK AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,50,13.0,08A,1151255.0,1941092.0,2024,01/15/2025 03:44:07 PM,41.994245,-87.718978,"(41.9942453, -87.718977985)"
174899,13686945,JH536243,2024-12-09 09:00:00,004XX E 87TH PL,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,8,44.0,08A,1180718.0,1847070.0,2024,12/21/2024 03:40:46 PM,41.735613,-87.613501,"(41.735612549, -87.613501096)"
185016,13702082,JH554952,2024-12-25 12:00:00,079XX S LAFLIN ST,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,17,71.0,08A,1167711.0,1852239.0,2024,01/02/2025 03:41:34 PM,41.750086,-87.661006,"(41.75008567, -87.66100576)"
224711,13764726,JJ168534,2025-03-03 10:45:00,028XX W 82ND ST,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,18,70.0,08A,1158900.0,1850126.0,2025,03/11/2025 03:41:34 PM,41.744472,-87.693351,"(41.744471661, -87.693350938)"
248315,13802575,JJ214115,2025-04-10 16:33:00,097XX S JEFFERY AVE,0583,STALKING,CYBERSTALKING,RESIDENCE,False,True,...,7,51.0,08A,1191214.0,1840764.0,2025,04/18/2025 03:42:00 PM,41.718061,-87.575252,"(41.718060932, -87.575251788)"

<h3> Converting Pandas Data Frame into Python List</h3>

In [163]:
stalking_heatmap = stalking_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [164]:
stalking_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [165]:
HeatMap(stalking_heatmap).add_to(stalking_map)

In [166]:
stalking_map.save('stalking.html')
print('data save to stalking.html')

data save to stalking.html

In [167]:
stalking_map

<h1 style="text-align: center; color: blue;">SLIQUOR LAW VIOLATION ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [168]:
liquor1= chicago[chicago['Primary Type'] == 'LIQUOR LAW VIOLATION']
liquor2 = liquor1[liquor1['Location Description'] == 'TAVERN / LIQUOR STORE' ]
liquor3 = liquor2[liquor2['Description'] == 'LIQUOR LICENSE VIOLATION' ]

<h1>DATA AGGREGATION</h1>

In [169]:
liquor_final = liquor3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
liquor_final

     Latitude  Longitude  incident_count
0   41.677831 -87.620504               2
1   41.684858 -87.658969               1
2   41.713390 -87.550621               1
3   41.729473 -87.662880               1
4   41.733274 -87.551336               1
5   41.750212 -87.674769               1
6   41.751506 -87.583995               1
7   41.756770 -87.653906               1
8   41.764677 -87.624888               1
9   41.765785 -87.611067               1
10  41.770981 -87.683413               1
11  41.773087 -87.608899               1
12  41.774070 -87.644639               1
13  41.778726 -87.718469               1
14  41.791351 -87.654803               1
15  41.793485 -87.705365               3
16  41.793490 -87.705156               1
17  41.800863 -87.664766               1
18  41.802009 -87.622030               1
19  41.809433 -87.613321               2
20  41.844228 -87.726467               2
21  41.851434 -87.732129               1
22  41.854394 -87.675907               1
23  41.855585 -87.711857               1
24  41.859036 -87.709650               1
25  41.866439 -87.702346               3
26  41.876410 -87.630734               3
27  41.880418 -87.751631               1
28  41.880682 -87.729435               1
29  41.891040 -87.632565               1
30  41.891046 -87.617951               1
31  41.891584 -87.634446               4
32  41.894844 -87.630462               1
33  41.896641 -87.630810               1
34  41.902991 -87.689798               1
35  41.908987 -87.652537               1
36  41.910239 -87.694846               1
37  41.923574 -87.798465               2
38  41.937807 -87.823056               1
39  41.938693 -87.757303               1
40  41.952271 -87.786531               1
41  41.953866 -87.712238               1
42  41.963772 -87.836693               1
43  41.968564 -87.694669               1
44  42.000182 -87.671318               1
45  42.017057 -87.690198               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [170]:
liquor_heatmap = liquor_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [171]:
liquor_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [172]:
HeatMap(liquor_heatmap).add_to(liquor_map)

In [173]:
liquor_map.save('liquor.html')
print('data save to liquor.html')

data save to liquor.html

In [174]:
liquor_map

<h1 style="text-align: center; color: blue;">PROSTITUTION ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [175]:
prostitution1 = chicago[chicago['Primary Type'] == 'PROSTITUTION']
prostitution2 = prostitution1[prostitution1['Location Description'] == 'STREET'] 
prostitution3 = prostitution2[prostitution2['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [176]:
prostitution_final = prostitution3.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
prostitution_final

      Latitude  Longitude  incident_count
0    41.694271 -87.620795               1
1    41.694404 -87.622404               1
2    41.694405 -87.622496               1
3    41.694415 -87.621500               1
4    41.694419 -87.621240               1
..         ...        ...             ...
120  41.879392 -87.737885               1
121  41.900840 -87.726556               1
122  41.900863 -87.724330               1
123  41.902546 -87.734298               1
124  41.905441 -87.726387               1

[125 rows x 3 columns]

<h3> Converting Pandas Data Frame into Python List</h3>

In [177]:
prostitution_heatmap = prostitution_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [178]:
prostitution_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [179]:
HeatMap(prostitution_heatmap).add_to(prostitution_map)

In [180]:
prostitution_map.save('prostitution.html')
print('data save to prostitution.html')

data save to prostitution.html

In [181]:
prostitution_map

<h1 style="text-align: center; color: blue;">GAMBLING ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [182]:
gambling1 = chicago[chicago['Primary Type'] == 'GAMBLING']
gambling2 = gambling1[gambling1['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [183]:
gambling_final = gambling2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
gambling_final

     Latitude  Longitude  incident_count
0   41.692359 -87.623097               1
1   41.692585 -87.622853               1
2   41.750095 -87.644027               1
3   41.750344 -87.664283               1
4   41.790516 -87.625597               1
5   41.790549 -87.625597               1
6   41.810171 -87.621236               1
7   41.810359 -87.606583               1
8   41.866657 -87.625811               1
9   41.876911 -87.628302               2
10  41.877802 -87.627668               1
11  41.880815 -87.752634               1
12  41.885599 -87.651350               1
13  41.885874 -87.625284               1
14  41.895539 -87.624266               1
15  41.899058 -87.721834               1
16  41.924613 -87.716310               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [184]:
gambling_heatmap = gambling_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [185]:
gambling_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [186]:
HeatMap(gambling_heatmap).add_to(gambling_map)

In [187]:
gambling_map.save('gambling.html')
print('data save to gambling.html')

data save to gambling.html

In [188]:
gambling_map

<h1 style="text-align: center; color: blue;">OBSCENITY ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [189]:
obscenity1 = chicago[chicago['Primary Type'] == 'OBSCENITY'] 
obscenity2 = obscenity1[obscenity1['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [190]:
obscenity_final = obscenity2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
obscenity_final

     Latitude  Longitude  incident_count
0   41.695192 -87.637617               1
1   41.732932 -87.548570               1
2   41.736427 -87.570855               1
3   41.742284 -87.715354               1
4   41.742684 -87.690745               1
5   41.761017 -87.643086               1
6   41.762429 -87.651622               1
7   41.770874 -87.591116               1
8   41.773548 -87.621513               1
9   41.776400 -87.570448               1
10  41.790622 -87.732888               1
11  41.791161 -87.579837               1
12  41.801864 -87.593461               1
13  41.813260 -87.689461               1
14  41.821180 -87.613501               1
15  41.822200 -87.602135               1
16  41.828762 -87.614436               1
17  41.839258 -87.623482               1
18  41.844200 -87.728537               1
19  41.850063 -87.696792               1
20  41.853192 -87.641350               1
21  41.855494 -87.623677               1
22  41.858780 -87.620788               1
23  41.863033 -87.627320               1
24  41.865947 -87.705655               1
25  41.868542 -87.639235               1
26  41.871107 -87.676371               1
27  41.879410 -87.631249               1
28  41.879643 -87.774640               1
29  41.884106 -87.674879               1
30  41.891865 -87.724760               1
31  41.891880 -87.754264               1
32  41.905063 -87.711748               1
33  41.918647 -87.646133               1
34  41.921642 -87.687979               1
35  41.922091 -87.692770               1
36  41.924622 -87.764782               1
37  41.925447 -87.725580               1
38  41.934532 -87.649708               1
39  41.935755 -87.695805               1
40  41.943221 -87.760155               1
41  41.951120 -87.706717               1
42  41.957479 -87.780597               1
43  41.958423 -87.655133               1
44  41.968970 -87.663350               1
45  41.970993 -87.687772               1
46  41.971209 -87.690207               1
47  41.979006 -87.906463               1
48  41.986927 -87.665460               1
49  41.990781 -87.673726               1
50  41.994149 -87.686478               1
51  42.006636 -87.668875               1
52  42.011249 -87.696008               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [191]:
obscenity_heatmap = obscenity_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [192]:
obscenity_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [193]:
HeatMap(obscenity_heatmap).add_to(obscenity_map)

In [194]:
obscenity_map.save('obscenity.html')
print('data save to obscenity.html')

data save to obscenity.html

In [195]:
obscenity_map

<h1 style="text-align: center; color: blue;">PUBLIC INDECENCY ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [196]:
indecency1 = chicago[chicago['Primary Type'] == 'PUBLIC INDECENCY']
indecency2 = indecency1[indecency1['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [197]:
indecency_final = indecency2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
indecency_final

     Latitude  Longitude  incident_count
0   41.695908 -87.595823               1
1   41.765785 -87.683271               1
2   41.768692 -87.624942               1
3   41.784515 -87.653412               1
4   41.796151 -87.759560               1
5   41.852024 -87.686627               1
6   41.852260 -87.670225               1
7   41.878170 -87.629107               1
8   41.962324 -87.684443               1
9   41.990128 -87.670852               1
10  41.990615 -87.683189               1
11  41.998734 -87.660613               1
12  42.016035 -87.668950               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [198]:
indecency_heatmap = indecency_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [199]:
indecency_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [200]:
HeatMap(indecency_heatmap).add_to(indecency_map)

In [201]:
indecency_map.save('indecency.html')
print('data save to indecency.html')

data save to indecency.html

In [202]:
indecency_map

<h1 style="text-align: center; color: blue;">HUMAN TRAFFICKING ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [203]:
humantraffic1 = chicago[chicago['Primary Type'] == 'HUMAN TRAFFICKING']
humantraffic2 = humantraffic1[humantraffic1['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [204]:
humantraffic_final = humantraffic2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
humantraffic_final

     Latitude  Longitude  incident_count
0   41.698903 -87.657123               1
1   41.746692 -87.665002               1
2   41.754477 -87.605283               1
3   41.783408 -87.643539               1
4   41.790895 -87.604940               1
5   41.797111 -87.652523               1
6   41.830428 -87.671999               1
7   41.841208 -87.646357               1
8   41.842673 -87.640407               1
9   41.846412 -87.698568               1
10  41.861359 -87.694400               1
11  41.868103 -87.716182               1
12  41.868618 -87.743632               1
13  41.870028 -87.708824               1
14  41.870504 -87.741210               1
15  41.874892 -87.751388               1
16  41.888426 -87.751691               1
17  41.912459 -87.667141               1
18  41.936441 -87.746793               2
19  41.969025 -87.718272               1
20  41.984679 -87.775959               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [205]:
humantraffic_heatmap = humantraffic_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [206]:
humantraffic_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [207]:
HeatMap(humantraffic_heatmap).add_to(humantraffic_map)

In [208]:
humantraffic_map.save('human_traffic.html')
print('data save to human_traffic.html')

data save to human_traffic.html

In [209]:
humantraffic_map

<h1 style="text-align: center; color: blue;">OTHER NARCOTIC VIOLATION ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [210]:
narcotic1 = chicago[chicago['Primary Type'] == 'OTHER NARCOTIC VIOLATION']
narcotic2 = narcotic1[narcotic1['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [211]:
narcotic_final = narcotic2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count')
narcotic_final

    Latitude  Longitude  incident_count
0  41.733650 -87.557845               1
1  41.739285 -87.625537               1
2  41.768214 -87.673617               1
3  41.857828 -87.661317               1
4  41.873699 -87.704705               1
5  41.928526 -87.648868               1
6  41.946542 -87.736084               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [212]:
narcotic_heatmap = narcotic_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [213]:
narcotic_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [214]:
HeatMap(narcotic_heatmap).add_to(narcotic_map)

In [215]:
narcotic_map.save('narcotic.html')
print('data save to narcotic.html')

data save to narcotic.html

In [216]:
narcotic_map

<h1 style="text-align: center; color: blue;">NON-CRIMINAL ANALYSIS</h1>

<h1>FILTERING DATA</h1>

In [217]:
noncriminal1 = chicago[chicago['Primary Type'] == 'NON-CRIMINAL'] 
noncriminal2 = noncriminal1[noncriminal1['Year'] >= 2024]

<h1>DATA AGGREGATION</h1>

In [218]:
noncriminal_final = noncriminal2.groupby(['Latitude', 'Longitude']).size().reset_index(name= 'incident_count') 
noncriminal_final

    Latitude  Longitude  incident_count
0  41.677619 -87.620499               1
1  41.876279 -87.627633               1
2  41.896802 -87.634210               1
3  41.998193 -87.660100               1

<h3> Converting Pandas Data Frame into Python List</h3>

In [219]:
noncriminal_heatmap = noncriminal_final[['Latitude','Longitude','incident_count']].values.tolist()

<h3> Creating a base map </h3>

In [220]:
noncriminal_map =  folium.Map(location = [42,-87], zoom_start = 7)

<h3> Add Heatmap Layer </h3>

In [221]:
HeatMap(noncriminal_heatmap).add_to(noncriminal_map)

In [222]:
noncriminal_map.save('non_criminal.html')
print('data save to non_criminal.html')

data save to non_criminal.html

In [223]:
noncriminal_map